using SyncSql.Core.Domain;
using SyncSql.Core.Serialization;

namespace SyncSql.Core.Tests.Serialization;

public sealed class ExtractedFileContractTests
{
    private static readonly ExtractedObject Object = new()
    {
        Server = "SQL",
        Database = "App",
        Schema = "dbo",
        Type = "Tables",
        Name = "Orders",
        Engine = DatabaseEngine.MsSql,
        Ddl = "CREATE TABLE dbo.Orders (Id int);",
    };

    [Theory]
    [InlineData(null, "Orders")]
    [InlineData("", "Orders")]
    [InlineData("dbo", "dbo.Orders")]
    public void WrittenHeaderPreservesHumanReadableIdentityAndSeparatesDdl(string? schema, string qualified)
    {
        string text = ExtractedObjectFile.Write(Object with { Schema = schema });
        Assert.StartsWith("-- Auto-generated by SyncSQL. Do not edit manually; changes will be overwritten.\n-- Path layout: schema/type\n-- Identity: ", text);
        Assert.Contains($"\n-- Server:   SQL\n-- Database: App\n-- Type:     Tables\n-- Object:   {qualified}\n-- Engine:   mssql\n\n{Object.Ddl}\n", text, StringComparison.Ordinal);
        Assert.DoesNotContain("-- ===", text, StringComparison.Ordinal);
    }

    [Fact]
    public void DenyAndColumnGrantMetadataAreWrittenAndRecovered()
    {
        GrantEntry grant = new("SELECT", GrantState.Deny, "reader", "DATABASE_ROLE", "Secret");
        string text = ExtractedObjectFile.Write(Object with { Grants = [grant] });
        Assert.Contains("\n\n-- === Grants ===\n-- [grant] SELECT|DENY|reader|DATABASE_ROLE|Secret\n", text, StringComparison.Ordinal);
        Assert.Equal(grant, Assert.Single(ExtractedObjectFile.Parse(text.Split('\n')).Grants));
    }

    [Fact]
    public void ColumnOnlyDescriptionSurvivesAlongsideUndocumentedColumns()
    {
        string text = ExtractedObjectFile.Write(Object with
        {
            Columns = [new("Id", "int", null), new("Secret", "text", "Sensitive")],
        });
        Assert.Contains("-- === Extended Properties ===\n-- [column: Secret] MS_Description = Sensitive\n", text, StringComparison.Ordinal);
        Assert.Equal("Sensitive", ExtractedObjectFile.Parse(text.Split('\n')).Columns.Single(column => column.Name == "Secret").Description);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData(" \t")]
    public void BlankDescriptionsDoNotCreateEmptyPropertySections(string? description)
    {
        string text = ExtractedObjectFile.Write(Object with { Columns = [new("Id", "int", description)] });
        Assert.DoesNotContain("-- === Extended Properties ===", text, StringComparison.Ordinal);
    }

    [Fact]
    public void ParserRecognizesCaseInsensitiveDescriptionPropertiesAndIgnoresUnrelatedProperties()
    {
        ParsedObjectFile parsed = ExtractedObjectFile.Parse([
            "-- Engine: mssql", "", "SELECT 1;", "",
            "-- === Extended Properties ===",
            "-- [object] Owner = wrong", "-- [object] ms_description = Object description",
            "-- [object] MS_Description = Later description",
            "-- [column: Id] Owner = wrong", "-- [column: Name] ms_description = Column description",
            "-- unrelated comment",
        ]);
        Assert.Equal("Object description", parsed.Description);
        Assert.Equal(new ExtractedColumn("Name", null, "Column description"), Assert.Single(parsed.Columns));
    }

    [Fact]
    public void ParserKeepsAdjacentSectionBodiesSeparate()
    {
        ParsedObjectFile parsed = ExtractedObjectFile.Parse([
            "-- Engine: mssql", "", "SELECT 1;", "",
            "-- === Indexes ===", "CREATE INDEX first;", "",
            "-- === Triggers ===", "CREATE TRIGGER second;",
        ]);
        Assert.Equal("SELECT 1;", parsed.Ddl);
        Assert.Equal([new ExtractedSection("Indexes", "CREATE INDEX first;"), new ExtractedSection("Triggers", "CREATE TRIGGER second;")], parsed.Sections);
    }

    [Theory]
    [InlineData("")]
    [InlineData("-- Engine: mssql")]
    [InlineData("-- Engine: mssql\n")]
    public void EmptyAndHeaderOnlyFilesHaveNoDdl(string text) =>
        Assert.Empty(ExtractedObjectFile.Parse(text.Split('\n')).Ddl);

    [Fact]
    public void EmptyLineSequenceHasNoDdl() => Assert.Empty(ExtractedObjectFile.Parse([]).Ddl);

    [Theory]
    [InlineData(".", "_")]
    [InlineData("..", "__")]
    public void RelativeDirectoryNamesCannotEscapeTheExportTree(string name, string expected) =>
        Assert.Equal(expected, ExtractedObjectFile.SafeFileName(name));

    [Fact]
    public void HeaderWithoutSeparatorDoesNotLoseTheFirstDdlLine() =>
        Assert.Equal("SELECT 1;\nSELECT 2;", ExtractedObjectFile.Parse(["-- Engine: mssql", "SELECT 1;", "SELECT 2;"]).Ddl);

    [Fact]
    public void EmptyExportAncestryFallsBackToTheServerName() =>
        Assert.Equal("SQL/App/dbo/Tables/Orders.sql", ExtractedObjectFile.RelativePath("SQL", "App", "dbo", "Tables", "Orders", serverPath: []));
}
