using SyncSql.Core.Domain;
using SyncSql.Core.Serialization;

namespace SyncSql.Core.Tests.Serialization;

public class ExtractedObjectFileTests
{
    [Fact]
    public void WriteThenParse_RoundTripsDdlColumnsGrantsSectionsAndEngine()
    {
        ExtractedObject original = new()
        {
            Server = "SQLPROD01",
            Database = "AppDb",
            Schema = "dbo",
            Type = "Tables",
            Name = "Orders",
            Ddl = "CREATE TABLE [dbo].[Orders] (\n    [OrderId] INT NOT NULL\n);",
            Engine = DatabaseEngine.MsSql,
            Description = "Order header table",
            Columns =
            [
                new ExtractedColumn("OrderId", "int", "Primary key"),
                new ExtractedColumn("CustomerId", "int", null),
            ],
            Grants = [new GrantEntry("SELECT", GrantState.Grant, "app_reader", "DATABASE_ROLE", null)],
            Sections = [new ExtractedSection("Foreign Keys", "ALTER TABLE [dbo].[Orders] ADD CONSTRAINT [FK_Orders_Customers] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([CustomerId]);")],
        };

        string fileContent = ExtractedObjectFile.Write(original);
        ParsedObjectFile parsed = ExtractedObjectFile.Parse(fileContent.Split('\n'));

        Assert.Equal(original.Ddl, parsed.Ddl);
        Assert.Equal(DatabaseEngine.MsSql, parsed.Engine);
        Assert.Equal("Order header table", parsed.Description);

        Assert.Equal(2, parsed.Columns.Count);
        Assert.Equal("Primary key", parsed.Columns.Single(c => c.Name == "OrderId").Description);
        Assert.Equal("int", parsed.Columns.Single(c => c.Name == "CustomerId").DataType);

        GrantEntry grant = Assert.Single(parsed.Grants);
        Assert.Equal("SELECT", grant.Permission);
        Assert.Equal(GrantState.Grant, grant.State);
        Assert.Equal("app_reader", grant.Grantee);
        Assert.Null(grant.Column);

        ExtractedSection section = Assert.Single(parsed.Sections);
        Assert.Equal("Foreign Keys", section.Title);
        Assert.Contains("FK_Orders_Customers", section.Content);
    }

    [Fact]
    public void Write_MultiLineDescription_IsCollapsedToOneLineAndStillParses()
    {
        ExtractedObject original = new()
        {
            Server = "SQLPROD01",
            Database = "AppDb",
            Schema = "dbo",
            Type = "Tables",
            Name = "Orders",
            Ddl = "CREATE TABLE [dbo].[Orders] ([OrderId] INT NOT NULL);",
            Engine = DatabaseEngine.MsSql,
            Description = "First line.\r\nSecond line.",
            Columns = [new ExtractedColumn("OrderId", "int", "Line A\nLine B")],
        };

        string fileContent = ExtractedObjectFile.Write(original);
        ParsedObjectFile parsed = ExtractedObjectFile.Parse(fileContent.Split('\n'));

        Assert.Equal("First line. Second line.", parsed.Description);
        Assert.Equal("Line A Line B", parsed.Columns.Single(c => c.Name == "OrderId").Description);
    }

    [Fact]
    public void Parse_FileWithoutEngineHeader_LeavesEngineNull()
    {
        string[] lines =
        [
            "-- Auto-generated by SyncSQL. Do not edit manually; changes will be overwritten.",
            "-- Server:   SQLPROD01",
            "-- Database: AppDb",
            "-- Type:     Views",
            "-- Object:   dbo.OrderSummary",
            "",
            "CREATE VIEW [dbo].[OrderSummary] AS SELECT 1;",
        ];

        ParsedObjectFile parsed = ExtractedObjectFile.Parse(lines);

        Assert.Null(parsed.Engine);
        Assert.Equal("CREATE VIEW [dbo].[OrderSummary] AS SELECT 1;", parsed.Ddl);
    }

    [Fact]
    public void Write_UsesLfLineEndings_RegardlessOfPlatform()
    {
        ExtractedObject original = new()
        {
            Server = "SQLPROD01",
            Database = "AppDb",
            Schema = "dbo",
            Type = "Tables",
            Name = "Orders",
            Ddl = "CREATE TABLE [dbo].[Orders] (\r\n    [OrderId] INT NOT NULL\r\n);",
            Engine = DatabaseEngine.MsSql,
            Columns = [new ExtractedColumn("OrderId", "int", null)],
            Sections = [new ExtractedSection("Indexes", "CREATE INDEX [IX_Orders_OrderId]\r\n    ON [dbo].[Orders] ([OrderId]);")],
        };

        string fileContent = ExtractedObjectFile.Write(original);

        // Windows and Linux extractions of the same object must produce byte-identical files, so
        // neither Environment.NewLine nor the source server's CRLF may leak into the output.
        Assert.DoesNotContain('\r', fileContent);
    }

    [Fact]
    public void Parse_CrlfFileSplitOnLf_StillRecoversEngineDescriptionColumnsAndSections()
    {
        string[] lines =
        [
            "-- Auto-generated by SyncSQL. Do not edit manually; changes will be overwritten.\r",
            "-- Server:   SQLPROD01\r",
            "-- Database: AppDb\r",
            "-- Type:     Tables\r",
            "-- Object:   dbo.Orders\r",
            "-- Engine:   mssql\r",
            "\r",
            "CREATE TABLE [dbo].[Orders] ([OrderId] INT NOT NULL);\r",
            "\r",
            "-- === Columns ===\r",
            "-- [col] OrderId|int\r",
            "\r",
            "-- === Grants ===\r",
            "-- [grant] SELECT|GRANT|app_reader|DATABASE_ROLE|\r",
            "\r",
            "-- === Extended Properties ===\r",
            "-- [object] MS_Description = Order header table\r",
        ];

        ParsedObjectFile parsed = ExtractedObjectFile.Parse(lines);

        Assert.Equal(DatabaseEngine.MsSql, parsed.Engine);
        Assert.Equal("CREATE TABLE [dbo].[Orders] ([OrderId] INT NOT NULL);", parsed.Ddl);
        Assert.Equal("Order header table", parsed.Description);
        Assert.Equal("int", Assert.Single(parsed.Columns).DataType);
        Assert.Equal("app_reader", Assert.Single(parsed.Grants).Grantee);
    }

    [Fact]
    public void RelativePath_OmitsSchemaSegmentWhenSchemaIsNull()
    {
        string path = ExtractedObjectFile.RelativePath("SQLPROD01", "master", schema: null, "LinkedServers", "ORAPROD01");

        Assert.Equal("SQLPROD01/master/LinkedServers/ORAPROD01.sql", path);
    }

    [Fact]
    public void ObjectId_StripsExtension()
    {
        string id = ExtractedObjectFile.ObjectId("SQLPROD01", "AppDb", "dbo", "Tables", "Orders");

        Assert.Equal("SQLPROD01/AppDb/Tables/dbo/Orders", id);
    }

    [Fact]
    public void SafeFileName_ReplacesInvalidCharsWithUnderscore()
    {
        string safe = ExtractedObjectFile.SafeFileName("weird:name?");

        Assert.DoesNotContain(':', safe);
        Assert.DoesNotContain('?', safe);
    }
}
