using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using SyncSql.Core.Domain;

namespace SyncSql.Core.Serialization;

/// <summary>Everything <see cref="ExtractedObjectFile.Parse"/> recovers from one extracted .sql file's text.</summary>
public sealed record ParsedObjectFile
{
    public required string Ddl { get; init; }
    public string? Description { get; init; }
    public IReadOnlyList<ExtractedColumn> Columns { get; init; } = [];
    public IReadOnlyList<GrantEntry> Grants { get; init; } = [];
    public IReadOnlyList<ExtractedSection> Sections { get; init; } = [];

    /// <summary>Null when the file predates the "-- Engine:" header - callers should degrade gracefully, not fail.</summary>
    public DatabaseEngine? Engine { get; init; }
}

/// <summary>
/// The on-disk format for one extracted object: a static header (no timestamps, so re-running the
/// extraction with no underlying database changes produces zero diff), the object's own DDL, and any
/// number of "-- === Title ==="-marked appended sections (Foreign Keys, Check Constraints, Indexes,
/// Columns, Grants, Extended Properties, ...). A direct port of SyncSql.Common.psm1's
/// New-SyncSqlObjectFile and Build-Catalog.ps1's ConvertFrom-SyncSqlObjectFileLines, kept together here
/// since they are two directions of the exact same format and drift easily if maintained apart.
/// </summary>
public static class ExtractedObjectFile
{
    private const string ColumnsTitle = "Columns";
    private const string GrantsTitle = "Grants";
    private const string ExtendedPropertiesTitle = "Extended Properties";

    private static readonly Regex MarkerPattern = new("^-- === (.+) ===$", RegexOptions.Compiled);
    private static readonly Regex EngineHeaderPattern = new(@"^-- Engine:\s*(\S+)$", RegexOptions.Compiled);
    private static readonly Regex ObjectPropertyPattern = new(@"^-- \[object\] (\S+) = (.*)$", RegexOptions.Compiled);
    private static readonly Regex ColumnPropertyPattern = new(@"^-- \[column: (.+?)\] (\S+) = (.*)$", RegexOptions.Compiled);
    private static readonly Regex ColumnLinePattern = new(@"^-- \[col\] ([^|]*)\|(.*)$", RegexOptions.Compiled);
    private static readonly Regex GrantLinePattern = new(@"^-- \[grant\] ([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|(.*)$", RegexOptions.Compiled);
    private static readonly Regex DescriptionPropertyName = new("Description", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>The deterministic relative path: server/database/[schema/]type/object.ext.</summary>
    public static string RelativePath(string server, string database, string? schema, string type, string name, string extension = "sql")
    {
        List<string> segments = [SafeFileName(server), SafeFileName(database)];
        if (!string.IsNullOrWhiteSpace(schema))
        {
            segments.Add(SafeFileName(schema));
        }

        segments.Add(SafeFileName(type));
        string fileName = $"{SafeFileName(name)}.{extension}";
        return string.Join('/', segments) + "/" + fileName;
    }

    /// <summary>Stable legacy identity, independent of export layout, preserving deep links and metrics history keys.</summary>
    public static string ObjectId(string server, string database, string? schema, string type, string name) =>
        string.Join('/', new[] { server, database, type, schema, name }.Where(s => !string.IsNullOrWhiteSpace(s)).Select(s => SafeFileName(s!)));

    // A fixed, explicit set rather than Path.GetInvalidFileNameChars(): that call is
    // platform-dependent (Unix only disallows '/' and NUL), and this tool now runs
    // cross-platform - the same object name must sanitize to the same file name
    // regardless of which OS extracted it, or the generated tree (and its git history)
    // would drift depending on which platform ran the extraction.
    private static readonly char[] InvalidFileNameChars =
        [.. "<>:\"/\\|?*", .. Enumerable.Range(0, 32).Select(c => (char)c)];

    public static string SafeFileName(string name)
    {
        StringBuilder builder = new(name.Length);
        foreach (char c in name)
        {
            builder.Append(Array.IndexOf(InvalidFileNameChars, c) >= 0 ? '_' : c);
        }

        return builder.ToString();
    }

    /// <summary>Renders one extracted object's full file content: header, DDL, and every appended section (Columns/Grants/Extended Properties reconstructed from the object's structured fields, plus any opaque Sections as-is).</summary>
    public static string Write(ExtractedObject obj)
    {
        // Every interpolation here is written invariantly on purpose: these files are the diffable
        // artifact the whole tool exists to produce, so their content must depend on the object, never
        // on the locale of the machine that happened to run the sync.
        StringBuilder builder = new();
        AppendLine(builder, "-- Auto-generated by SyncSQL. Do not edit manually; changes will be overwritten.");
        AppendLine(builder, "-- Path layout: schema/type");
        AppendLine(builder, Invariant($"-- Server:   {obj.Server}"));
        AppendLine(builder, Invariant($"-- Database: {obj.Database}"));
        AppendLine(builder, Invariant($"-- Type:     {obj.Type}"));
        AppendLine(builder, Invariant($"-- Object:   {obj.QualifiedName}"));
        AppendLine(builder, Invariant($"-- Engine:   {obj.Engine.ToConfigString()}"));
        AppendLine(builder);
        AppendLine(builder, NormalizeNewLines(obj.Ddl).Trim());

        foreach (ExtractedSection section in obj.Sections)
        {
            AppendSection(builder, section.Title, [NormalizeNewLines(section.Content)]);
        }

        if (obj.Columns.Count > 0)
        {
            AppendSection(builder, ColumnsTitle, obj.Columns.Select(c => $"-- [col] {c.Name}|{c.DataType}"));
        }

        if (obj.Grants.Count > 0)
        {
            AppendSection(builder, GrantsTitle, obj.Grants.Select(g =>
                $"-- [grant] {g.Permission}|{(g.State == GrantState.Deny ? "DENY" : "GRANT")}|{g.Grantee}|{g.GranteeType}|{g.Column}"));
        }

        bool hasColumnDescriptions = obj.Columns.Any(c => !string.IsNullOrWhiteSpace(c.Description));
        if (!string.IsNullOrWhiteSpace(obj.Description) || hasColumnDescriptions)
        {
            List<string> propertyLines = [];
            if (!string.IsNullOrWhiteSpace(obj.Description))
            {
                propertyLines.Add($"-- [object] MS_Description = {SingleLine(obj.Description)}");
            }

            foreach (ExtractedColumn column in obj.Columns)
            {
                if (!string.IsNullOrWhiteSpace(column.Description))
                {
                    propertyLines.Add($"-- [column: {column.Name}] MS_Description = {SingleLine(column.Description)}");
                }
            }

            AppendSection(builder, ExtendedPropertiesTitle, propertyLines);
        }

        return builder.ToString();
    }

    /// <summary>
    /// The property-line format is strictly one line per property - a multi-line MS_Description written
    /// raw would push its continuation lines outside the "-- " comment format (dropped by Parse, and
    /// left as stray non-comment text in a .sql file), so newlines are collapsed to single spaces.
    /// </summary>
    private static string SingleLine(string value) =>
        value.ReplaceLineEndings(" ").Trim();

    /// <summary>Formats one interpolated line invariantly: the header values are the file's content, so they must read the same whatever locale the sync happened to run under.</summary>
    private static string Invariant(FormattableString line) =>
        line.ToString(CultureInfo.InvariantCulture);

    // The file format is LF-terminated on every platform, deliberately not Environment.NewLine:
    // the same object extracted on Windows and on Linux must produce byte-identical files, or the
    // generated tree shows a whole-file diff for every object the moment the extraction moves
    // between machines - exactly the churn the timestamp-free header exists to avoid.
    private static void AppendLine(StringBuilder builder, string line = "") =>
        builder.Append(line).Append('\n');

    /// <summary>Collapses CRLF and lone CR to LF, so DDL and section text coming out of the database carry the file format's line ending rather than the source server's.</summary>
    private static string NormalizeNewLines(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');

    private static void AppendSection(StringBuilder builder, string title, IEnumerable<string> contentLines)
    {
        AppendLine(builder);
        AppendLine(builder, Invariant($"-- === {title} ==="));
        foreach (string line in contentLines)
        {
            AppendLine(builder, line);
        }
    }

    /// <summary>Parses one extracted .sql file's full text back into its structured pieces - the inverse of <see cref="Write"/>.</summary>
    public static ParsedObjectFile Parse(IEnumerable<string> lines)
    {
        // A trailing CR (a CRLF file split on '\n' by the caller, or a file committed with CRLF and
        // read back through `git show`) would otherwise defeat every '$'-anchored pattern below -
        // silently costing the engine header and every "-- === Title ===" section, description,
        // column and grant included - so line endings are normalized here rather than trusted.
        string[] allLines = [.. lines.Select(line => line.EndsWith('\r') ? line[..^1] : line)];
        if (allLines.Length > 0)
        {
            // StreamReader strips a byte-order mark, so File.ReadAllLines never shows one - but
            // `git show` hands back the blob's bytes verbatim, and files written by the PowerShell
            // extractor this format was ported from carry a UTF-8 BOM. Left in place it would break
            // the '-- ' header scan on the very first line, pulling the whole header into the DDL
            // and losing the engine with it.
            allLines[0] = allLines[0].TrimStart('\uFEFF');
        }

        int i = 0;
        DatabaseEngine? engine = null;
        while (i < allLines.Length && allLines[i].StartsWith("-- ", StringComparison.Ordinal))
        {
            Match engineMatch = EngineHeaderPattern.Match(allLines[i]);
            if (engineMatch.Success && DatabaseEngineNames.TryParse(engineMatch.Groups[1].Value, out DatabaseEngine parsedEngine))
            {
                engine = parsedEngine;
            }

            i++;
        }
        if (i < allLines.Length && allLines[i].Length == 0)
        {
            i++;
        }

        string[] bodyLines = allLines[i..];

        List<(int Index, string Title)> markers = [];
        for (int j = 0; j < bodyLines.Length; j++)
        {
            Match match = MarkerPattern.Match(bodyLines[j]);
            if (match.Success)
            {
                markers.Add((j, match.Groups[1].Value));
            }
        }

        string[] ddlLines = markers.Count > 0 ? bodyLines[..markers[0].Index] : bodyLines;

        // A Dictionary (not a List<(string,string[])>) specifically so "section not found" is a clean
        // TryGetValue false rather than a defaulted value tuple - FirstOrDefault on a value-tuple
        // sequence returns a zeroed-out tuple, not a true null, so an "is not null" check against a
        // nullable-tuple wrapper around it is always true and silently masks the not-found case.
        Dictionary<string, string[]> sections = [];
        for (int k = 0; k < markers.Count; k++)
        {
            int start = markers[k].Index + 1;
            int end = k + 1 < markers.Count ? markers[k + 1].Index : bodyLines.Length;
            sections.TryAdd(markers[k].Title, bodyLines[start..end]);
        }

        string? description = null;
        Dictionary<string, string> columnDescriptions = [];
        if (sections.TryGetValue(ExtendedPropertiesTitle, out string[]? extendedPropertiesLines))
        {
            foreach (string line in extendedPropertiesLines)
            {
                Match objectMatch = ObjectPropertyPattern.Match(line);
                if (objectMatch.Success)
                {
                    if (DescriptionPropertyName.IsMatch(objectMatch.Groups[1].Value) && description is null)
                    {
                        description = objectMatch.Groups[2].Value;
                    }
                    continue;
                }

                Match columnMatch = ColumnPropertyPattern.Match(line);
                if (columnMatch.Success && DescriptionPropertyName.IsMatch(columnMatch.Groups[2].Value))
                {
                    columnDescriptions[columnMatch.Groups[1].Value] = columnMatch.Groups[3].Value;
                }
            }
        }

        List<ExtractedColumn> fullColumns = [];
        if (sections.TryGetValue(ColumnsTitle, out string[]? columnsSectionLines))
        {
            foreach (string line in columnsSectionLines)
            {
                Match match = ColumnLinePattern.Match(line);
                if (match.Success)
                {
                    string name = match.Groups[1].Value;
                    columnDescriptions.TryGetValue(name, out string? columnDescription);
                    fullColumns.Add(new ExtractedColumn(name, match.Groups[2].Value, columnDescription));
                }
            }
        }

        IReadOnlyList<ExtractedColumn> columns = fullColumns.Count > 0
            ? fullColumns
            : [.. columnDescriptions.Select(kv => new ExtractedColumn(kv.Key, null, kv.Value))];

        List<GrantEntry> grants = [];
        if (sections.TryGetValue(GrantsTitle, out string[]? grantsSectionLines))
        {
            foreach (string line in grantsSectionLines)
            {
                Match match = GrantLinePattern.Match(line);
                if (!match.Success)
                {
                    continue;
                }

                string stateText = match.Groups[2].Value;
                GrantState state = string.Equals(stateText, "DENY", StringComparison.OrdinalIgnoreCase) ? GrantState.Deny : GrantState.Grant;
                string? granteeType = match.Groups[4].Value is { Length: > 0 } gt ? gt : null;
                string? column = match.Groups[5].Value is { Length: > 0 } col ? col : null;
                grants.Add(new GrantEntry(match.Groups[1].Value, state, match.Groups[3].Value, granteeType, column));
            }
        }

        // Walk markers (not the sections dictionary) for this pass specifically to preserve on-disk
        // order - Dictionary enumeration order is an implementation detail, not a contract, and section
        // order matters for how the object detail page displays FK/Check Constraints/Indexes.
        List<ExtractedSection> otherSections = [];
        HashSet<string> seenTitles = [];
        foreach ((_, string title) in markers)
        {
            if (title is ExtendedPropertiesTitle or ColumnsTitle or GrantsTitle || !seenTitles.Add(title))
            {
                continue;
            }

            otherSections.Add(new ExtractedSection(title, string.Join('\n', sections[title]).Trim()));
        }

        return new ParsedObjectFile
        {
            Ddl = string.Join('\n', ddlLines).Trim(),
            Description = description,
            Columns = columns,
            Grants = grants,
            Sections = otherSections,
            Engine = engine,
        };
    }
}
