using System.Text;
using System.Text.RegularExpressions;
using SyncSql.Core.Domain;

namespace SyncSql.Core.Serialization;

/// <summary>Everything <see cref="ExtractedObjectFile.Parse"/> recovers from one extracted .sql file's text.</summary>
public sealed record ParsedObjectFile
{
    public required string Ddl { get; init; }
    public string? Description { get; init; }
    public IReadOnlyList<ExtractedColumn> Columns { get; init; } = [];
    public IReadOnlyList<GrantEntry> Grants { get; init; } = [];
    public IReadOnlyList<ExtractedSection> Sections { get; init; } = [];

    /// <summary>Null when the file predates the "-- Engine:" header - callers should degrade gracefully, not fail.</summary>
    public DatabaseEngine? Engine { get; init; }
}

/// <summary>
/// The on-disk format for one extracted object: a static header (no timestamps, so re-running the
/// extraction with no underlying database changes produces zero diff), the object's own DDL, and any
/// number of "-- === Title ==="-marked appended sections (Foreign Keys, Check Constraints, Indexes,
/// Columns, Grants, Extended Properties, ...). A direct port of SyncSql.Common.psm1's
/// New-SyncSqlObjectFile and Build-Catalog.ps1's ConvertFrom-SyncSqlObjectFileLines, kept together here
/// since they are two directions of the exact same format and drift easily if maintained apart.
/// </summary>
public static class ExtractedObjectFile
{
    private const string ColumnsTitle = "Columns";
    private const string GrantsTitle = "Grants";
    private const string ExtendedPropertiesTitle = "Extended Properties";

    private static readonly Regex MarkerPattern = new("^-- === (.+) ===$", RegexOptions.Compiled);
    private static readonly Regex EngineHeaderPattern = new(@"^-- Engine:\s*(\S+)$", RegexOptions.Compiled);
    private static readonly Regex ObjectPropertyPattern = new(@"^-- \[object\] (\S+) = (.*)$", RegexOptions.Compiled);
    private static readonly Regex ColumnPropertyPattern = new(@"^-- \[column: (.+?)\] (\S+) = (.*)$", RegexOptions.Compiled);
    private static readonly Regex ColumnLinePattern = new(@"^-- \[col\] ([^|]*)\|(.*)$", RegexOptions.Compiled);
    private static readonly Regex GrantLinePattern = new(@"^-- \[grant\] ([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|(.*)$", RegexOptions.Compiled);
    private static readonly Regex DescriptionPropertyName = new("Description", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>The deterministic, diff-friendly relative path for one object: server/database/type/[schema/]object.ext.</summary>
    public static string RelativePath(string server, string database, string? schema, string type, string name, string extension = "sql")
    {
        List<string> segments = [SafeFileName(server), SafeFileName(database), SafeFileName(type)];
        if (!string.IsNullOrWhiteSpace(schema))
        {
            segments.Add(SafeFileName(schema));
        }

        string fileName = $"{SafeFileName(name)}.{extension}";
        return string.Join('/', segments) + "/" + fileName;
    }

    /// <summary>The catalog node id for one object - RelativePath with the extension stripped, e.g. "SQLPROD01/AppDb/Tables/dbo/Orders". Also used as the metrics snapshot/history file key.</summary>
    public static string ObjectId(string server, string database, string? schema, string type, string name) =>
        RelativePath(server, database, schema, type, name)[..^".sql".Length];

    // A fixed, explicit set rather than Path.GetInvalidFileNameChars(): that call is
    // platform-dependent (Unix only disallows '/' and NUL), and this tool now runs
    // cross-platform - the same object name must sanitize to the same file name
    // regardless of which OS extracted it, or the generated tree (and its git history)
    // would drift depending on which platform ran the extraction.
    private static readonly char[] InvalidFileNameChars =
        [.. "<>:\"/\\|?*", .. Enumerable.Range(0, 32).Select(c => (char)c)];

    public static string SafeFileName(string name)
    {
        StringBuilder builder = new(name.Length);
        foreach (char c in name)
        {
            builder.Append(Array.IndexOf(InvalidFileNameChars, c) >= 0 ? '_' : c);
        }

        return builder.ToString();
    }

    /// <summary>Renders one extracted object's full file content: header, DDL, and every appended section (Columns/Grants/Extended Properties reconstructed from the object's structured fields, plus any opaque Sections as-is).</summary>
    public static string Write(ExtractedObject obj)
    {
        StringBuilder builder = new();
        builder.AppendLine("-- Auto-generated by SyncSQL. Do not edit manually; changes will be overwritten.");
        builder.AppendLine($"-- Server:   {obj.Server}");
        builder.AppendLine($"-- Database: {obj.Database}");
        builder.AppendLine($"-- Type:     {obj.Type}");
        builder.AppendLine($"-- Object:   {obj.QualifiedName}");
        builder.AppendLine($"-- Engine:   {obj.Engine.ToConfigString()}");
        builder.AppendLine();
        builder.AppendLine(obj.Ddl.Trim());

        foreach (ExtractedSection section in obj.Sections)
        {
            AppendSection(builder, section.Title, [section.Content]);
        }

        if (obj.Columns.Count > 0)
        {
            AppendSection(builder, ColumnsTitle, obj.Columns.Select(c => $"-- [col] {c.Name}|{c.DataType}"));
        }

        if (obj.Grants.Count > 0)
        {
            AppendSection(builder, GrantsTitle, obj.Grants.Select(g =>
                $"-- [grant] {g.Permission}|{(g.State == GrantState.Deny ? "DENY" : "GRANT")}|{g.Grantee}|{g.GranteeType}|{g.Column}"));
        }

        bool hasColumnDescriptions = obj.Columns.Any(c => !string.IsNullOrWhiteSpace(c.Description));
        if (!string.IsNullOrWhiteSpace(obj.Description) || hasColumnDescriptions)
        {
            List<string> propertyLines = [];
            if (!string.IsNullOrWhiteSpace(obj.Description))
            {
                propertyLines.Add($"-- [object] MS_Description = {obj.Description}");
            }

            foreach (ExtractedColumn column in obj.Columns)
            {
                if (!string.IsNullOrWhiteSpace(column.Description))
                {
                    propertyLines.Add($"-- [column: {column.Name}] MS_Description = {column.Description}");
                }
            }

            AppendSection(builder, ExtendedPropertiesTitle, propertyLines);
        }

        return builder.ToString();
    }

    private static void AppendSection(StringBuilder builder, string title, IEnumerable<string> contentLines)
    {
        builder.AppendLine();
        builder.AppendLine($"-- === {title} ===");
        foreach (string line in contentLines)
        {
            builder.AppendLine(line);
        }
    }

    /// <summary>Parses one extracted .sql file's full text back into its structured pieces - the inverse of <see cref="Write"/>.</summary>
    public static ParsedObjectFile Parse(IEnumerable<string> lines)
    {
        string[] allLines = [.. lines];
        int i = 0;
        DatabaseEngine? engine = null;
        while (i < allLines.Length && allLines[i].StartsWith("-- ", StringComparison.Ordinal))
        {
            Match engineMatch = EngineHeaderPattern.Match(allLines[i]);
            if (engineMatch.Success && DatabaseEngineNames.TryParse(engineMatch.Groups[1].Value, out DatabaseEngine parsedEngine))
            {
                engine = parsedEngine;
            }

            i++;
        }
        if (i < allLines.Length && allLines[i].Length == 0)
        {
            i++;
        }

        string[] bodyLines = allLines[i..];

        List<(int Index, string Title)> markers = [];
        for (int j = 0; j < bodyLines.Length; j++)
        {
            Match match = MarkerPattern.Match(bodyLines[j]);
            if (match.Success)
            {
                markers.Add((j, match.Groups[1].Value));
            }
        }

        string[] ddlLines = markers.Count > 0 ? bodyLines[..markers[0].Index] : bodyLines;

        // A Dictionary (not a List<(string,string[])>) specifically so "section not found" is a clean
        // TryGetValue false rather than a defaulted value tuple - FirstOrDefault on a value-tuple
        // sequence returns a zeroed-out tuple, not a true null, so an "is not null" check against a
        // nullable-tuple wrapper around it is always true and silently masks the not-found case.
        Dictionary<string, string[]> sections = [];
        for (int k = 0; k < markers.Count; k++)
        {
            int start = markers[k].Index + 1;
            int end = k + 1 < markers.Count ? markers[k + 1].Index : bodyLines.Length;
            sections.TryAdd(markers[k].Title, bodyLines[start..end]);
        }

        string? description = null;
        Dictionary<string, string> columnDescriptions = [];
        if (sections.TryGetValue(ExtendedPropertiesTitle, out string[]? extendedPropertiesLines))
        {
            foreach (string line in extendedPropertiesLines)
            {
                Match objectMatch = ObjectPropertyPattern.Match(line);
                if (objectMatch.Success)
                {
                    if (DescriptionPropertyName.IsMatch(objectMatch.Groups[1].Value) && description is null)
                    {
                        description = objectMatch.Groups[2].Value;
                    }
                    continue;
                }

                Match columnMatch = ColumnPropertyPattern.Match(line);
                if (columnMatch.Success && DescriptionPropertyName.IsMatch(columnMatch.Groups[2].Value))
                {
                    columnDescriptions[columnMatch.Groups[1].Value] = columnMatch.Groups[3].Value;
                }
            }
        }

        List<ExtractedColumn> fullColumns = [];
        if (sections.TryGetValue(ColumnsTitle, out string[]? columnsSectionLines))
        {
            foreach (string line in columnsSectionLines)
            {
                Match match = ColumnLinePattern.Match(line);
                if (match.Success)
                {
                    string name = match.Groups[1].Value;
                    columnDescriptions.TryGetValue(name, out string? columnDescription);
                    fullColumns.Add(new ExtractedColumn(name, match.Groups[2].Value, columnDescription));
                }
            }
        }

        IReadOnlyList<ExtractedColumn> columns = fullColumns.Count > 0
            ? fullColumns
            : [.. columnDescriptions.Select(kv => new ExtractedColumn(kv.Key, null, kv.Value))];

        List<GrantEntry> grants = [];
        if (sections.TryGetValue(GrantsTitle, out string[]? grantsSectionLines))
        {
            foreach (string line in grantsSectionLines)
            {
                Match match = GrantLinePattern.Match(line);
                if (!match.Success)
                {
                    continue;
                }

                string stateText = match.Groups[2].Value;
                GrantState state = string.Equals(stateText, "DENY", StringComparison.OrdinalIgnoreCase) ? GrantState.Deny : GrantState.Grant;
                string? granteeType = match.Groups[4].Value is { Length: > 0 } gt ? gt : null;
                string? column = match.Groups[5].Value is { Length: > 0 } col ? col : null;
                grants.Add(new GrantEntry(match.Groups[1].Value, state, match.Groups[3].Value, granteeType, column));
            }
        }

        // Walk markers (not the sections dictionary) for this pass specifically to preserve on-disk
        // order - Dictionary enumeration order is an implementation detail, not a contract, and section
        // order matters for how the object detail page displays FK/Check Constraints/Indexes.
        List<ExtractedSection> otherSections = [];
        HashSet<string> seenTitles = [];
        foreach ((_, string title) in markers)
        {
            if (title is ExtendedPropertiesTitle or ColumnsTitle or GrantsTitle || !seenTitles.Add(title))
            {
                continue;
            }

            otherSections.Add(new ExtractedSection(title, string.Join('\n', sections[title]).Trim()));
        }

        return new ParsedObjectFile
        {
            Ddl = string.Join('\n', ddlLines).Trim(),
            Description = description,
            Columns = columns,
            Grants = grants,
            Sections = otherSections,
            Engine = engine,
        };
    }
}
